displayName=Ultimate Stat Tracker
author=ProbWontMax
description=Tracks a plethora of stats across account lifetime
tags=stats,tracker,number,dopamine,lifetime,logs,ore,fish,damage,collecting,processing
plugins=com.ultimatestattracker