package com.ultimatestattracker;

public class StatKeys {
     public static String EXAMINE = "itemsExamined";
     public static String ITEMS_DROPPED = "itemsDropped";
     public static String SHOP_GP_SPENT = "shopGpSpent";
     public static String SHOP_GP_GAINED = "shopGpGained";
     public static String SPELLS_CAST = "spellsCast";
     public static String TELEPORTS_CAST = "teleportsCast";
     public static String TILES_WALKED = "tilesWalked";
     public static String TILES_RAN = "tilesRan";
     public static String FISH_CAUGHT = "fishCaught";
     public static String ROCKS_MINED = "rocksMined";
     public static String LOGS_CHOPPED = "logsChopped";
     public static String BONES_BURIED = "bonesBuried";
     public static String BONES_CRUSHED = "bonesCrushed";
     public static String ASHES_SCATTERED = "ashesScattered";
     public static String LOGS_BURNED = "logsBurned";
     public static String TOTAL_DEATHS = "totalDeaths";
     public static String FOOD_EATEN = "foodEaten";
     public static String HP_REGEN = "hpRegen";
     public static String BEER_DRANK = "beerDrank";
     public static String CABBAGE_EATEN = "cabbageEaten";
     public static String TROUT_EATEN = "troutEaten";
     public static String FLAX_PICKED = "flaxPicked";
     public static String CABBAGE_PICKED = "cabbagePicked";
     public static String CRITTERS_PET = "crittersPet";
     public static String POTION_SIPS_DRANK = "potionSips";
     public static String VIALS_SMASHED = "vialsSmashed";
     public static String PICK_POCKETS = "pickPockets";
     public static String STALLS_THIEVED = "stallsThieved";
     public static String WEEDS_RAKED = "weedsRaked";
     public static String SEEDS_PLANTED = "seedsPlanted";
     public static String MELEE_ATTACKS_LANDED = "meleeAttacksLanded";
     public static String ROOF_TOP_AGILITY = "rooftopAgilityLaps";
     public static String NORMAL_AGILITY = "normalAgilityLaps";
     public static String IMPLINGS_CAUGHT = "implingsCaught";
     public static String FOOD_COOKED = "foodCooked";
     public static String FOOD_BURNED = "foodBurned";
     public static String FAILED_PICK_POCKETS = "failedPickPockets";
     public static String UNFINISHED_POTIONS_MADE = "unfinishedPotionsMade";
     public static String POTIONS_MADE = "potionsMade";
}
